### ISSUE TITLE
Change .env -> .env_example

### ISSUE THREAD

**Issue by harrison-symes** [leslie-alldridge/auth-cats#2]
`cp .env .env_example`
`echo .env >> .gitignore`

Add a line to README for running 
`mv .env_example .env` for setup

This way the boilerplate can provide an env example, but still have .env in gitignore like is intended

**Comment by leslie-alldridge** [comment]
Thanks @harrison-symes I'll look into these now - for some strange reason I didn't receive any notifications re: these issues

**Comment by leslie-alldridge** [comment]
.env added to ignore, file replaced with env example, readme updated.
