### ISSUE TITLE
Folder structure changes

### ISSUE THREAD

**Issue by harrison-symes** [leslie-alldridge/auth-cats#3]
This might be a better way of sorting things
| src
| -- components/
| -- --  auth/
| -- -- -- Register.jsx
| -- -- cats/
| -- -- -- AddCat.jsx
|
| -- actions/
| -- -- auth/
| -- -- -- register.js
| -- -- cats/
| -- -- -- addCat.js

**Comment by leslie-alldridge** [comment]
structure implemented and imports updated (wish I had auto import updates turned on in vs code on my mac 👍)
